mysql:
  username: ${DATABASE_MYSQL_USERNAME}
  password: ${DATABASE_MYSQL_PASSWORD}
  schema: ${DATABASE_MYSQL_TABLE}
  url: ${DATABASE_MYSQL_HOST}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none